### ISSUE TITLE
无法生成成功

### ISSUE THREAD

**Issue by shuijinliuxi** [YaoZeyuan/ZhihuHelp__Python#13]
匹配用户提问数/回答数/专栏数/收藏夹数/公共编辑数失败
错误内容:
need more than 0 values to unpack
超时页面http://www.zhihu.com/people/qiao-er-53/answers?order_by=vote_num&page=49
正在读取答案页面，还有3/67张页面等待读取
正在读取答案页面，还有3/67张页面等待读取
打开网页超时
超时页面http://www.zhihu.com/people/qiao-er-53/answers?order_by=vote_num&page=25
答案录入数据库成功
匹配用户提问数/回答数/专栏数/收藏夹数/公共编辑数失败
错误内容:
need more than 0 values to unpack
匹配用户关注数/被关注数失败
错误内容:
need more than 0 values to unpack
匹配用户赞同数/感谢数/被收藏数/被分享数失败
错误内容:
need more than 0 values to unpack
正在读取答案页面，还有2/67张页面等待读取
正在读取答案页面，还有1/67张页面等待读取
答案录入数据库成功
没有收集到指定问题
错误信息:
'NoneType' object has no attribute '__getitem__'

这是该链接：http://www.zhihu.com/people/qiao-er-53/answers

**Comment by YaoZeyuan** [comment]
已修复：）
