### ISSUE TITLE
下载最新源码运行失败

### ISSUE THREAD

**Issue by shuijinliuxi** [YaoZeyuan/ZhihuHelp__Python#14]
python zhihuHelp.py 
Traceback (most recent call last):
  File "zhihuHelp.py", line 6, in <module>
    import bs4
ImportError: No module named bs4

从上面得出少了bs4模块，我的是OS X系统，怎么导入呢

**Comment by YaoZeyuan** [comment]
先等等，我在debug

**Comment by YaoZeyuan** [comment]
ok，基本搞定了，我一会儿再把setting模块写下，写完就可以运行了

**Comment by shuijinliuxi** [comment]
这样重新下载最新的需不需要自己安装其他的环境呢

**Comment by YaoZeyuan** [comment]
嗯，不用

**Comment by YaoZeyuan** [comment]
建议用pyCharm打开。这样直接导入工程就行，就不用在额外配置东西了：）

**Comment by YaoZeyuan** [comment]
OK了，现在代码已经可以正常运行了
话说，这个月因为赶工期，写的并不好- -
一星期之后再来看或许会好些：）
嘿嘿
