### ISSUE TITLE
正常使用时报错退出

### ISSUE THREAD

**Issue by zhaochunqi** [YaoZeyuan/ZhihuHelp__Python#20]
hi, 下载收藏夹 http://www.zhihu.com/collection/61913303 时，会报错退出，报错信息如图（Mac OSX EI python 2.7.10): 
<img width="576" alt="screen shot 2015-11-23 at 4 48 46 am" src="https://cloud.githubusercontent.com/assets/4682835/11326193/ce9afcba-919d-11e5-8c0a-32661a48cf21.png">

另外，下载示例提供的网址生成的epub中也有报错信息。

**Comment by YaoZeyuan** [comment]
感谢反馈，可以试下新版助手：）
