### ISSUE TITLE
含tex页面还是报错，错误代码11001

### ISSUE THREAD

**Issue by horizonl** [YaoZeyuan/ZhihuHelp__Python#22]
如这篇专栏http://zhuanlan.zhihu.com/everytingisphysics ，总显示网络连接异常，不知为何

**Comment by YaoZeyuan** [comment]
我一会儿发个新版，新版里面会修复tex图片下载失败的错误
现在的问题是tex图片是知乎服务器实时生成的，但服务器生成速度太慢，每次都是time out - -
这估计就无解了。。。
