### ISSUE TITLE
生成epub中图片重复

### ISSUE THREAD

**Issue by daoxunchen** [YaoZeyuan/ZhihuHelp__Python#23]
你好，非常感谢。
http://www.zhihu.com/question/20502275我在下载这个问题下的答案时，正常生成epub文件，但其中的答案中的图片都重复了一次，答主头像正常。
在版本1.7.2和1.7.3中都有这种情况。在1.7.2中，使用高清图片模式和普通图片模式都有重复。
不知道这个问题怎么解决？

**Comment by YaoZeyuan** [comment]
嗯，这是因为知乎网页里把图片在<noscript>标签里又写了一遍，本来应该是隐藏掉的，但有的阅读器把它显示出来了，看起来就是图片重复了两次
已经在最新版助手中移除了这个标签了
感谢反馈：）
