### ISSUE TITLE
答案中代码块的显示问题

### ISSUE THREAD

**Issue by knarfeh** [YaoZeyuan/ZhihuHelp__Python#4]
self.content = content.replace('\r', '').replace('\n', '')  

是不是用这一行代码把缩进什么的都删掉了？这样的话，如果答案中有缩进的代码就会比较难看，比如：
![default](https://cloud.githubusercontent.com/assets/6964284/7833045/3d99598a-0496-11e5-83e4-c6bb54ec84c8.png)
理想的是这样的：
![default](https://cloud.githubusercontent.com/assets/6964284/7833197/84b3a248-0497-11e5-98da-5b22abde8ff8.png)

我也在想办法解决，不知道有什么坑需要注意？

**Comment by YaoZeyuan** [comment]
嗯，确实是这样的。应该把这行代码注释掉，然后用多行模式进行正则匹配，这样效果能好些。
坑的话，可能需要检查下带上\n\r之后正则表达式的正确性吧，不过估计没啥问题：）

**Comment by YaoZeyuan** [comment]
这个做起来有点困难。之前的正则都是按照单行匹配的模式做的，换成多行匹配之后正确性存疑，我准备写一个单元测试去解决这个问题

**Comment by YaoZeyuan** [comment]
![123](https://cloud.githubusercontent.com/assets/7150325/11708061/2c1ac130-9f46-11e5-8c36-f2e91efba723.png)

**Comment by YaoZeyuan** [comment]
现在生成单张页面的时候还有点问题，我晚上回家把这个bug解掉

**Comment by YaoZeyuan** [comment]
已修复
