### ISSUE TITLE
下载专栏后打开生成的epub显示损坏

### ISSUE THREAD

**Issue by shuijinliuxi** [YaoZeyuan/ZhihuHelp__Python#5]
下载专栏后打开生成的epub显示损坏，重复下载了几次，都一样，在手机上能打开，但是基本只有专栏的标题和损坏的图片

**Comment by knarfeh** [comment]
我试了一下，用火狐的ePub打开的，没有问题，你用的是什么软件？

**Comment by shuijinliuxi** [comment]
用的是mac上的iBook，现在试了好几个软件，在mac上现在能正常使用的只有calibre和bookReader，其他试过的都不行，window和iphone上暂时还没找到能正常阅读的，现在手机采取的就是用calibre把epub再转成pdf看

**Comment by knarfeh** [comment]
用iBook确实有问题，我没用Mac，但是用同学的试过。Windows的话，刚试了一下Chrome的Readium，也可以打开，iPad的话，用多看和Documents可以打开，iPhone没试，用多看应该可以。有时间我再看看具体是什么原因。

**Comment by shuijinliuxi** [comment]
iphone上用多看试了下，可以运行

**Comment by YaoZeyuan** [comment]
手里没有苹果设备，没法测试iBook，暂时先用多看吧：）
