### ISSUE TITLE
抓取答案内容时，忽略了一种图片格式，导致程序异常

### ISSUE THREAD

**Issue by knarfeh** [YaoZeyuan/ZhihuHelp__Python#6]
例如这个问题：[十行以内，你写过哪些比较酷的 Mathematica 代码？ ](http://www.zhihu.com/question/27890699)中用到了一个公式，写出来是这样的<img eeimg="1" alt="(n,m,l)=(4,0,3)" src="http://zhihu.com/equation?tex=%28n%2Cm%2Cl%29%3D%284%2C0%2C3%29"> 

根据dict2Html.py中的
```
def imgFix(self, content):
        for imgTag in re.findall(r'<img.*?>', content):
            src = re.search(r'(?<=src=").*?(?=")', imgTag)
...
```
和
```
def getFileName(self, imgHref = ''):
        return imgHref.split('/')[-1]
```
得到的fileName为：equation?tex=%28n%2Cm%2Cl%29%3D%284%2C0%2C3%29，无法建立图片文件，如：
![imgpool](https://cloud.githubusercontent.com/assets/6964284/7986951/41b62a7a-0b0d-11e5-8b0d-36b645ea0bd2.png)
程序运行结果为：
![result](https://cloud.githubusercontent.com/assets/6964284/7986973/598608fa-0b0d-11e5-8e09-8a29d850bb3b.png)

**Comment by YaoZeyuan** [comment]
感谢反馈~这个bug看起来有点难度，要慢慢做了：）

**Comment by YaoZeyuan** [comment]
已解决
