### ISSUE TITLE
部分答案抓取不下来，遗漏好多，是什么情况？

### ISSUE THREAD

**Issue by wimzyc** [YaoZeyuan/ZhihuHelp__Python#8]
比如说在readlist中加入这个URL：

http://www.zhihu.com/question/31064773

抓取到的答案数经过清点只有37个，在浏览器下用正常模式访问知乎时，显示答案有127个（截止到目前），那么就说明大部分答案都遗漏了。

另外，线程数如果设置为1，貌似会进入死循环，无法正常抓取

**Comment by YaoZeyuan** [comment]
已修复：）
